- name: Ansible Variables
  hosts: localhost
  vars:
    course: "Ansible"
    Trainer: "Hari"
    Duration: "120hrs"
  tasks:
  - name: Print Data Using Variables
    ansible.builtin.debug:
      msg: "The Course name is:{{course}},Trainer is:{{Trainer}} and the Duartion is: {{Duration}}"
