- name: Variables with Prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please Enter User Name
    private: false
  - name: PASSWORD
    prompt: Please Enter Password
    private: true
  tasks:
  - name: Print Prompting info
    ansible.builtin.debug:
      msg: "Hi Username:{{USERNAME}},Password:{{PASSWORD}}"
