- name: Instlla or uninstall Packages
  hosts: localhost
  become: yes

  tasks: 
  - name: Install or uninstall below list of Packages
    ansible.builtin.dnf:
      name: 
      state: 
    loop:
    - {name: 'mysql', state: 'latest'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}